retriever:
  model_name_or_path: openbmb/MiniCPM-Embedding-Light
  backend_configs:
    infinity:
      bettertransformer: false
      pooling_method: auto
      model_warmup: false
      trust_remote_code: true
    sentence_transformers:
      trust_remote_code: true
      sentence_transformers_encode:
        normalize_embeddings: false
        encode_chunk_size: 256
        q_prompt_name: query
        psg_prompt_name: document
        psg_task: null
        q_task: null
    openai:
      model_name: text-embedding-3-small
      base_url: https://api.openai.com/v1
      api_key: abc
      concurrency: 8
    bm25:
      lang: en
      save_path: index/bm25
  batch_size: 16
  corpus_path: data/corpus_example.jsonl
  gpu_ids: '1'
  is_multimodal: false
  backend: sentence_transformers
  index_backend: faiss
  index_backend_configs:
    faiss:
      index_use_gpu: true
      index_chunk_size: 10000
      index_path: index/index.index
    milvus:
      uri: index/milvus_demo.db
      token: null
      id_field_name: id
      vector_field_name: vector
      text_field_name: contents
      id_max_length: 64
      text_max_length: 60000
      metric_type: IP
      index_params:
        index_type: AUTOINDEX
        metric_type: IP
      search_params:
        metric_type: IP
        params: {}
      index_chunk_size: 1000
  is_demo: false
  collection_name: wiki
  embedding_path: embedding/embedding.npy
  overwrite: false
