import streamlit as st
def t(key):
    """Returns text based on current language"""
    if "config" not in st.session_state: st.session_state.config = {}
    lang = st.session_state.config.get('language', 'en')
    return LANGUAGE_MAP.get(key, {}).get(lang, key)

LANGUAGE_MAP = {
    "Retrieval Evaluation": {"en": "Retrieval Evaluation", "zh": "检索评测"},
    "Pooling Strategy": {"en": "Pooling Strategy", "zh": "池化策略"},
    "Select the pooling strategy to use.": {"en": "Select the pooling strategy to use.", "zh": "选择要使用的池化策略。"},
    "Query Instruction": {"en": "Query Instruction", "zh": "查询指令"},
    "Instruction to extract query text.": {"en": "Instruction to extract query text.", "zh": "提取查询文本的指令。"},
    "Queries File Path": {"en": "Queries File Path", "zh": "查询文件路径"},
    "Path to the queries file.": {"en": "Path to the queries file.", "zh": "查询文件的路径。"},
    "Corpus File Path": {"en": "Corpus File Path", "zh": "语料库文件路径"},
    "Path to the corpus file.": {"en": "Path to the corpus file.", "zh": "语料库文件的路径。"},
    "Qrels File Path": {"en": "Qrels File Path", "zh": "Qrels 文件路径"},
    "Path to the qrels file.": {"en": "Path to the qrels file.", "zh": "Qrels 文件的路径。"},
    "Output Results Path": {"en": "Output Results Path", "zh": "输出结果路径"},
    "Path to save the output results.": {"en": "Path to save the output results.", "zh": "保存输出结果的路径。"},
    "Log File Path": {"en": "Log File Path", "zh": "日志文件路径"},
    "Path to save the log file (optional).": {"en": "Path to save the log file (optional).", "zh": "保存日志文件的路径（可选）。"},
    "Top K Documents": {"en": "Top K Documents", "zh": "Top K 文档"},
    "Top k documents to retrieve.": {"en": "Top k documents to retrieve.", "zh": "要检索的前 K 个文档。"},
    "Cutoffs": {"en": "Cutoffs", "zh": "截断值"},
    "Cutoff for evaluation metrics, separated by commas (e.g., 10,20,50).": {"en": "Cutoff for evaluation metrics, separated by commas (e.g., 10,20,50).", "zh": "评测指标的截断值，用逗号分隔（例如，10,20,50）。"},
    "Pooling": {"en": "Pooling", "zh": "池化方法"},
    "Pooling method.": {"en": "Pooling method.", "zh": "池化方法。"},
    "Query Instrustion": {"en": "Query Instrustion", "zh": "查询指令"},
    "Query Instrustion.": {"en": "Query Instrustion.", "zh": "查询指令。"},
    "Select Language": {"en": "Select Language", "zh": "选择语言"},
    "Select LLM Model": {"en": "Select LLM Model", "zh": "选择LLM模型"},
    "Select Embedding Model": {"en": "Select Embedding Model", "zh": "选择Embedding模型"},
    "Select Reranker Model": {"en": "Select Reranker Model", "zh": "选择Reranker模型"},
    "LLM Model": {"en": "LLM Model", "zh": "LLM模型"},
    "Select CUDA Devices for": {"en": "Select CUDA Devices for", "zh": "选择CUDA设备用于"},
    "No CUDA devices available": {"en": "No CUDA devices available", "zh": "无可用CUDA设备"},
    "Model Name": {"en": "Model Name", "zh": "模型名称"},
    "API Key": {"en": "API Key", "zh": "API密钥"},
    "Base URL": {"en": "Base URL", "zh": "基础URL"},
    "Model Path": {"en": "Model Path", "zh": "模型路径"},
    "Specify the model path.": {"en": "Specify the model path.", "zh": "指定模型路径"},
    "Reranker Model Path": {"en": "Reranker Model Path", "zh": "Reranker模型路径"},
    "Select CUDA Devices for": {"en": "Select CUDA Devices for", "zh": "选择CUDA设备用于"},
    "NVIDIA SMI Monitor": {"en": "NVIDIA SMI Monitor", "zh": "NVIDIA SMI 监控"},
    "Status: Idle": {"en": "Status: Idle", "zh": "状态：空闲"},
    "Status: Watching...": {"en": "Status: Watching...", "zh": "状态：监控中..."},
    "Start Watch": {"en": "Start Watch", "zh": "开始监控"},
    "Stop Watch": {"en": "Stop Watch", "zh": "停止监控"},
    "Global Settings": {"en": "Global Settings", "zh": "全局设置"},
    "Model Manage": {"en": "Model Manage", "zh": "模型管理"},
    "Knowledge Base Manage": {"en": "Knowledge Base Manage", "zh": "知识库管理"},
    "Load LLM Model": {"en": "Load LLM Model", "zh": "加载LLM模型"},
    "Load Embedding Model": {"en": "Load Embedding Model", "zh": "加载Embedding模型"},
    "Load Reranker Model": {"en": "Load Reranker Model", "zh": "加载Reranker模型"},
    "Loading": {"en": "Loading", "zh": "加载中"},
    "Error": {"en": "Error", "zh": "错误"},
    "File Management": {"en": "File Management", "zh": "文件管理"},
    "File Management CSV Path": {"en": "File Management CSV Path", "zh": "文件管理 CSV 路径"},
    "File Save Path": {"en": "File Save Path", "zh": "文件保存路径"},
    "Upload Files": {"en": "Upload Files", "zh": "上传文件"},
    "Uploaded Successfully": {"en": "Uploaded Successfully", "zh": "上传成功"},
    "Remove Selected Files": {"en": "Remove Selected Files", "zh": "删除选中文件"},
    "File Deleted Successfully": {"en": "File Deleted Successfully", "zh": "文件删除成功"},
    "No File Found": {"en": "No File Found", "zh": "未找到文件"},
    "Collection Management": {"en": "Collection Management", "zh": "知识库管理"},
    "Collection Management CSV Path": {"en": "Collection Management CSV Path", "zh": "知识库管理 CSV 路径"},
    "Collection Save Path": {"en": "Collection Save Path", "zh": "知识库保存路径"},
    "Collection Name": {"en": "Collection Name", "zh": "知识库名称"},
    "Others (JSON Format)": {"en": "Others (JSON Format)", "zh": "其他参数 (JSON 格式)"},
    "Chunk Size": {"en": "Chunk Size", "zh": "块大小"},
    "Overlap": {"en": "Overlap", "zh": "重叠率"},
    "Embedding Name": {"en": "Embedding Name", "zh": "Embedding模型名称"},
    "Save & Build": {"en": "Save & Build", "zh": "保存并构建"},
    "Please load the embedding model.": {"en": "Please load the embedding model.","zh": "请加载Embedding模型。"},
    "Collection Params Saved Successfully！": {"en": "Collection Params Saved Successfully!","zh": "知识库参数保存成功！"},
    "Others Params Must Be Json Format": {"en": "Others Params Must Be Json Format","zh": "其他参数必须为 JSON 格式"},
    "No Collection Available": {"en": "No Collection Available","zh": "没有可用的知识库"},
    "File Lists": {"en": "File Lists","zh": "文件列表"},
    "Collection Lists": {"en": "Collection Lists","zh": "知识库列表"},
    "Collection Params Existed, Ignored": {"en": "Collection Params {kb_id} Existed, Ignored","zh": "集合参数 {kb_id} 已存在，已忽略"},
    "File Existed, Ignored": {"en": "File {file_name} Existed, Ignored", "zh": "文件 {file_name} 已存在，已忽略"},
    "Phase": {"en": "Phase", "zh": "阶段"},
    "Data Construction": {"en": "Data Construction", "zh": "数据构造"},
    "Train": {"en": "Train", "zh": "训练"},
    "Evaluation": {"en": "Evaluation", "zh": "评测"},
    "Terminal": {"en": "Terminal", "zh": "终端"},
    "Preview Command": {"en": "Preview Command", "zh": "预览指令"},
    "Command Preview": {"en": "Command Preview", "zh": "预览指令"},
    "Run Command": {"en": "Run Command", "zh": "运行指令"},
    "Running...": {"en": "Running...", "zh": "运行中..."},
    "Terminal": {"en": "Terminal", "zh": "终端"},
    "Command execution failed.": {"en": "Command execution failed.", "zh": "指令执行失败"},
    "Select Collection": {"en": "Select Collection", "zh": "选择知识库"},
    "Please Configure/Load Collection First": {"en": "Please Configure/Load Collection First", "zh": "请先配置/加载知识库"},
    "Please wait while the model is loading.": {"en": "Please wait while the model is loading.", "zh": "请等待模型加载"},
    "Preview of File": {"en": "Preview of {file} (Page {page}/{total_pages})","zh": "预览 {file}（第 {page}/{total_pages} 页）"},
    "Items per page": {"en": "Items per page","zh": "每页项目数"},
    "Set the number of items displayed per page.": {"en": "Set the number of items displayed per page.","zh": "设置每页显示的项目数。"},
    "Previous": {"en": "Previous","zh": "上一页"},
    "Next": {"en": "Next","zh": "下一页"},
    "Jump to page": {"en": "Jump to page","zh": "跳转到页"},
    "Enter the page number to jump to.": {"en": "Enter the page number to jump to.","zh": "输入要跳转到的页码。"},
    "Select pipeline:": {"en": "Select pipeline:", "zh": "选择方法："},
    "Configuration Path": {"en": "Configuration Path", "zh": "配置文件路径"},
    "Output Dir": {"en": "Output Dir", "zh": "输出文件夹"},
    "Specify the path for saving output files.": {"en": "Specify the path for saving output files.", "zh": "指定输出文件存放位置"},
    "Specify the output directory.": {"en": "Specify the output directory.", "zh": "指定输出文件夹"},
    "Specify the path for saving or loading configurations.": {"en": "Specify the path for saving or loading configurations.", "zh": "指定保存或加载配置文件的路径。"},
    "Output Path": {"en": "Output Path", "zh": "输出文件路径"},
    "Corpus Path": {"en": "Corpus Path", "zh": "语料路径"},
    "Path to the raw chunk data.": {"en": "Path to the raw chunk data.", "zh": "切片数据路径"},
    "Path to save the output.": {"en": "Path to save the output.", "zh": "保存输出文件路径"},
    "Load Config": {"en": "Load Config", "zh": "加载配置"},
    "Save Config": {"en": "Save Config", "zh": "保存配置"},
    "Please config the knowledge base.": {"en": "Please configure the knowledge base.", "zh": "请配置知识库"},
    "kb_csv_path": {"en": "kb_csv_path", "zh": "知识库CSV路径"},
    "Common Config": {"en": "Common Config", "zh": "通用配置"},
    "Pipeline Config": {"en": "Pipeline Config", "zh": "方法配置"},
    "Configuration saved to path.": {"en": "Configuration saved to {path}.", "zh": "配置已保存到 {path}。"},
    "Error saving configuration: error.": {"en": "Error saving configuration: {error}.", "zh": "保存配置时出错：{error}。"},
    "Configuration loaded from path.": {"en": "Configuration loaded from {path}.", "zh": "配置已从 {path} 加载。"},
    "Configuration file not found: path.": {"en": "Configuration file not found: {path}.", "zh": "未找到配置文件：{path}。"},
    "Error loading configuration: error.": {"en": "Error loading configuration: {error}.", "zh": "加载配置时出错：{error}。"},
    "Chat/Inference": {"en": "Chat/Inference", "zh": "聊天/推理"},
    "clear history": {"en": "clear history", "zh": "清除历史"},
    "Please load the model and select the collections": {"en": "Please load the model and select the collections", "zh": "请加载模型并选择知识库"},
    "Welcome to ": {"en": "Welcome to ", "zh": "欢迎使用"},
    "Please input your question": {"en": "Please input your question", "zh": "请输入您的问题"},
    "LoRA Merge": {"en": "LoRA Merge", "zh": "LoRA 合并"},
    "Model Name or Path": {"en": "Model Name or Path", "zh": "模型名称或路径"},
    "Path to the base model or model name.": {"en": "Path to the base model or model name.", "zh": "基础模型路径或名称。"},
    "Path to the LLM model or model name.": {"en": "Path to the LLM model or model name.", "zh": "LLM模型路径或名称。"},
    "LoRA Name or Path": {"en": "LoRA Name or Path", "zh": "LoRA 名称或路径"},
    "Path to the LoRA checkpoint.": {"en": "Path to the LoRA checkpoint.", "zh": "LoRA 检查点路径。"},
    "Save Path": {"en": "Save Path", "zh": "保存路径"},
    "Path to save the merged model.": {"en": "Path to save the merged model.", "zh": "保存合并模型的路径。"},
    "Select Test Datasets": {"en": "Select Test Datasets", "zh": "选择测试数据集"},
    "Select datasets to include in the test configuration.": {"en": "Select datasets to include in the test configuration.", "zh": "选择要包含在测试配置中的数据集。"},
    "Retrieval Metrics": {"en": "Retrieval Metrics", "zh": "检索指标"},
    "Select the retrieval metrics to evaluate (e.g., precision, recall).": {"en": "Select the retrieval metrics to evaluate (e.g., precision, recall).", "zh": "选择要评测的检索指标（例如，精确率、召回率）。"},
    "Preview Selected Datasets": {"en": "Preview Selected Datasets", "zh": "预览选定的数据集"},
    "No datasets selected to preview.": {"en": "No datasets selected to preview.", "zh": "未选择任何数据集进行预览。"},
    "Generated Metrics": {"en": "Generated Metrics", "zh": "生成指标"},
    "Select the generated metrics to evaluate (e.g., BLEU, ROUGE).": {"en": "Select the generated metrics to evaluate (e.g., BLEU, ROUGE).", "zh": "选择要评测的生成指标（例如，BLEU、ROUGE）。"},
    "Additional Config": {"en": "Additional Config", "zh": "额外配置"},
    "Evaluate Only": {"en": "Evaluate Only", "zh": "仅评测"},
    "If set, skip generation and directly evaluate datasets.": {"en": "If set, skip generation and directly evaluate datasets.", "zh": "如果设置，将跳过生成并直接评测数据集。"},
    "API key for authentication.": {"en": "API key for authentication.", "zh": "API 密钥。"},
    "API key for the main evaluation.": {"en": "API key for the main evaluation.", "zh": "被评测模型的 API 密钥。"},
    "Metric API Key": {"en": "Metric API Key", "zh": "指标模型 API 密钥"},
    "API key for metric evaluation.": {"en": "API key for metric evaluation.", "zh": "指标评测模型的 API 密钥。"},
    "Embedding Model Path": {"en": "Embedding Model Path", "zh": "Embedding模型路径"},
    "Path to the embedding model.": {"en": "Path to the embedding model.", "zh": "Embedding模型的路径。"},
    "Base URL": {"en": "Base URL", "zh": "基础 URL"},
    "Base URL for the evaluation service.": {"en": "Base URL for the evaluation service.", "zh": "评测服务的基础 URL。"},
    "Metric Base URL": {"en": "Metric Base URL", "zh": "指标基础 URL"},
    "Base URL for metric evaluation service.": {"en": "Base URL for metric evaluation service.", "zh": "指标评测服务的基础 URL。"},
    "Reranker Model Path": {"en": "Reranker Model Path", "zh": "Reranker模型路径"},
    "Path to the reranker model.": {"en": "Path to the reranker model.", "zh": "Reranker模型的路径。"},
    "Model name for the main evaluation.": {"en": "Model name for the main evaluation.", "zh": "主评测的模型名称。"},
    "Metric Model Name": {"en": "Metric Model Name", "zh": "评测模型名称"},
    "Model name for metric evaluation.": {"en": "Model name for metric evaluation.", "zh": "指标评测的模型名称。"},
    "Configuration": {"en": "Configuration", "zh": "参数配置"},
    "Training Data": {"en": "Training Data", "zh": "训练数据"},
    "Specify the path to training data.": {"en": "Specify the path to training data.", "zh": "指定训练数据路径"},
    "Train Group Size": {"en": "Train Group Size", "zh": "训练组大小"},
    "Set the train group size.": {"en": "Set the train group size.", "zh": "设置训练组大小。"},
    "Sentence Pooling Method": {"en": "Sentence Pooling Method", "zh": "句子池化方法"},
    "Specify the sentence pooling method.": {"en": "Specify the sentence pooling method.", "zh": "指定句子池化方法。"},
    "Learning Rate": {"en": "Learning Rate", "zh": "学习率"},
    "Set the learning rate.": {"en": "Set the learning rate.", "zh": "设置学习率。"},
    "Epochs": {"en": "Epochs", "zh": "训练轮次"},
    "Set the number of training epochs.": {"en": "Set the number of training epochs.", "zh": "设置训练轮次。"},
    "Batch Size": {"en": "Batch Size", "zh": "批量大小"},
    "Set the batch size.": {"en": "Set the batch size.", "zh": "设置批量大小。"},
    "Query Max Length": {"en": "Query Max Length", "zh": "查询最大长度"},
    "Specify the maximum query length.": {"en": "Specify the maximum query length.", "zh": "指定查询的最大长度。"},
    "Logging Steps": {"en": "Logging Steps", "zh": "日志记录间隔"},
    "Specify logging steps interval.": {"en": "Specify logging steps interval.", "zh": "指定日志记录的间隔。"},
    "Save Steps": {"en": "Save Steps", "zh": "保存间隔"},
    "Specify save steps interval.": {"en": "Specify save steps interval.", "zh": "指定保存的间隔。"},
    "Use LoRA": {"en": "Use LoRA", "zh": "使用 LoRA"},
    "Enable or disable LoRA.": {"en": "Enable or disable LoRA.", "zh": "启用或禁用 LoRA。"},
    "Select Train Datasets": {"en": "Select Train Datasets", "zh": "选择训练数据集"},
    "Select Eval Datasets": {"en": "Select Eval Datasets", "zh": "选择评测数据集"},
    "Select datasets to include in the test configuration.": {"en": "Select datasets to include in the test configuration.", "zh": "选择要包含在测试配置中的数据集。"},
    "Preview Selected train Datasets": {"en": "Preview Selected train Datasets", "zh": "预览选定的训练数据集"},
    "Preview Selected eval Datasets": {"en": "Preview Selected eval Datasets", "zh": "预览选定的评测数据集"},
    "No datasets selected to preview.": {"en": "No datasets selected to preview.", "zh": "未选择任何数据集进行预览。"},
    "Select CUDA Devices": {"en": "Select CUDA Devices", "zh": "选择 CUDA 设备"},
    "Select the GPUs you want to use.": {"en": "Select the GPUs you want to use.", "zh": "选择要使用的 GPU。"},
    "DeepSpeed Config File": {"en": "DeepSpeed Config File", "zh": "DeepSpeed 配置文件"},
    "Specify the DeepSpeed configuration file path.": {"en": "Specify the DeepSpeed configuration file path.", "zh": "指定 DeepSpeed 配置文件路径。"},
    "Master Port": {"en": "Master Port", "zh": "主端口"},
    "Specify the master port.": {"en": "Specify the master port.", "zh": "指定主端口。"},
    "Logging Directory": {"en": "Logging Directory", "zh": "日志存放目录"},
    "Specify the logging directory.": {"en": "Specify the logging directory.", "zh": "指定日志存放目录。"},
    "YAML Config File": {"en": "YAML Config File", "zh": "YAML 配置文件"},
    "Specify the YAML configuration file path.": {"en": "Specify the YAML configuration file path.", "zh": "指定 YAML 配置文件路径。"},
    "Log File": {"en": "Log File", "zh": "日志文件"},
    "Specify the log file path.": {"en": "Specify the log file path.", "zh": "指定日志文件路径。"},
    "Select Files from Output Folder (Full Paths)": {"en": "Select Files from Output Folder (Full Paths)", "zh": "从输出文件夹中选择文件（完整路径）"},
    "Select files from the output folder or add your own full paths.": {"en": "Select files from the output folder or add your own full paths.", "zh": "从输出文件夹中选择文件或添加自己的完整路径。"},
    "Or Enter Full Paths (one per line)": {"en": "Or Enter Full Paths (one per line)", "zh": "或输入完整路径（每行一个）"},
    "Enter additional full paths, one per line.": {"en": "Enter additional full paths, one per line.", "zh": "输入额外的完整路径，每行一个。"},
    "Output File": {"en": "Output File", "zh": "输出文件"},
    "Specify the name of the output file.": {"en": "Specify the name of the output file.", "zh": "指定输出文件的名称。"},
    "Ratios (e.g., [1, 2, 3])": {"en": "Ratios (e.g., [1, 2, 3])", "zh": "比例（例如：[1, 2, 3]）"},
    "Specify the ratios for data splits, e.g., [1, 2, 3].": {"en": "Specify the ratios for data splits, e.g., [1, 2, 3].", "zh": "指定数据分割的比例，例如：[1, 2, 3]。"},
    "Fixed Steps": {"en": "Fixed Steps", "zh": "固定步长"},
    "Specify the fixed step size for merging.": {"en": "Specify the fixed step size for merging.", "zh": "指定合并的固定步长。"},
    "Random Merge": {"en": "Random Merge", "zh": "随机合并"},
    "clustering": {"en": "clustering", "zh": "是否需要聚类（异质数据）"},
    "Enable or disable random merging.": {"en": "Enable or disable random merging.", "zh": "启用或禁用随机合并。"},
    "Output Format": {"en": "Output Format", "zh": "输出格式"},
    "Choose the output format.": {"en": "Choose the output format.", "zh": "选择输出格式。"},
    "Language": {"en": "Language", "zh": "语言"}, 
    "Select the language": {"en": "Select the language.", "zh": "选择语言。"}, 
    "Train Model Name or Path": {"en": "Train Model Name or Path", "zh": "训练模型名称或路径"},
    "Data Model Name or Path": {"en": "Data Model Name or Path", "zh": "数据模型名称或路径"},
    "Path to the model to be trained.": {"en": "Path to the model to be trained.", "zh": "要训练的模型路径。"},
    "Config Path": {"en": "Config Path", "zh": "配置路径"},
    "Path to the YAML configuration file.": {"en": "Path to the YAML configuration file.", "zh": "YAML 配置文件路径。"},
    "Train Output Path": {"en": "Train Output Path", "zh": "训练集输出路径"},
    "Path to save the train data JSONL file.": {"en": "Path to save the train data JSONL file.", "zh": "保存训练数据 JSONL 文件的路径。"},
    "Dev Output Path": {"en": "Dev Output Path", "zh": "验证集输出路径"},
    "Path to save the dev data JSONL file.": {"en": "Path to save the dev data JSONL file.", "zh": "保存开发数据 JSONL 文件的路径。"},
    "Functions to Run": {"en": "Functions to Run", "zh": "选择运行函数"},
    "Select which functions to run (e.g., function_q, function_qr).": {"en": "Select which functions to run (e.g., function_q, function_qr).", "zh": "选择要运行的函数（例如：function_q, function_qr）。"},
    "Ratios (Space-separated)": {"en": "Ratios (Space-separated)", "zh": "比例（以空格分隔）"},
    "Proportions for each file in format 1:2:3.": {"en": "Proportions for each file in format 1:2:3.", "zh": "每个文件的比例格式，例如 1:2:3。"},
    "Search Start Index": {"en": "Search Start Index", "zh": "搜索起始索引"},
    "Start index for search.": {"en": "Start index for search.", "zh": "搜索的起始索引。"},
    "Max Negative Score": {"en": "Max Negative Score", "zh": "最大负分"},
    "Maximum negative score.": {"en": "Maximum negative score.", "zh": "允许的最大负分。"},
    "Keep Negative Number": {"en": "Keep Negative Number", "zh": "保留负样本数量"},
    "Number of negatives to keep.": {"en": "Number of negatives to keep.", "zh": "保留的负样本数量。"},
    "QRel Path": {"en": "QRel Path", "zh": "QRel 路径"},
    "Path to the qrel data.": {"en": "Path to the qrel data.", "zh": "QRel 数据的路径。"},
    "Search End Index": {"en": "Search End Index", "zh": "搜索结束索引"},
    "End index for search.": {"en": "End index for search.", "zh": "搜索的结束索引。"},
    "Min Positive Score": {"en": "Min Positive Score", "zh": "最小正分"},
    "Minimum positive score.": {"en": "Minimum positive score.", "zh": "允许的最小正分。"},
    "Score Ratio": {"en": "Score Ratio", "zh": "得分比率"},
    "Ratio for scoring.": {"en": "Ratio for scoring.", "zh": "用于评分的比率。"},
    "Score Margin": {"en": "Score Margin", "zh": "得分边距"},
    "Margin for scoring.": {"en": "Margin for scoring.", "zh": "用于评分的边距。"},
    "Query Num per Corpus": {"en": "Query Num per Corpus", "zh": "每个语料库的查询数"},
    "Number of queries per corpus.": {"en": "Number of queries per corpus.", "zh": "每个语料库的查询数量。"},
    "Negs End Index": {"en": "Negs End Index", "zh": "负样本结束索引"},
    "End index for negative samples.": {"en": "End index for negative samples.", "zh": "负样本的结束索引。"},
    "Query Path": {"en": "Query Path", "zh": "查询路径"},
    "Path to save the queries.": {"en": "Path to save the queries.", "zh": "保存查询的路径。"},
    "Input Pair Path": {"en": "Input Pair Path", "zh": "输入对路径"},
    "Path to the input pair data.": {"en": "Path to the input pair data.", "zh": "输入对数据的路径。"},
    "Corpus Sample Num": {"en": "Corpus Sample Num", "zh": "语料库样本数"},
    "Number of corpus samples (default: -1 for all samples).": {"en": "Number of corpus samples (default: -1 for all samples).", "zh": "语料库样本数（默认：-1 表示所有样本）。"},
    "Shot File": {"en": "Shot File", "zh": "示例文件"},
    "Path to the shot file.": {"en": "Path to the shot file.", "zh": "示例文件的路径。"},
    "Negs Start Index": {"en": "Negs Start Index", "zh": "负样本起始索引"},
    "Start index for negative samples.": {"en": "Start index for negative samples.", "zh": "负样本的起始索引。"},
    "Input Prompt Path": {"en": "Input Prompt Path", "zh": "输入提示路径"},
    "Path to the input prompts.": {"en": "Path to the input prompts.", "zh": "输入提示的路径。"},
    "Select Metric Model": {"en": "Select Metric Model", "zh": "选择指标模型"}
}
